[blog]
title       = "{{ blog_title }}"
base_url    = "{{ blog_base_url }}"
author      = "{{ blog_author }}"
language    = "{{ blog_lang }}"
spa_enabled = {{ spa_enabled }}

[languages]
en = "English"
it = "Italiano"
fr = "Français"
es = "Español"
de = "Deutsch"

[home]
label  = "Home"
icon   = "fa-solid fa-home"

[audio]
enabled         = true
soundtracks_dir = "./assets/soundtracks"

[theme]
name                 = "default"
templates_dir        = "./templates"

[server]
port    = {{ rocket_port }}
address = "127.0.0.1"

[admin]
enabled = {{ admin_enabled }}
token   = "{{ admin_token }}"
