[blog]
title       = "My new blog"
base_url    = "http://localhost"
author      = "Admin"
language    = "en"
spa_enabled = true

[languages]
en = "English"
it = "Italiano"
fr = "Français"
es = "Español"
de = "Deutsch"

[home]
label  = "Home"
icon   = "fa-solid fa-home"

[audio]
enabled         = true
soundtracks_dir = "./assets/soundtracks"

[theme]
name                 = "default"
templates_dir        = "./templates"

[server]
port    = 8000
address = "127.0.0.1"

[admin]
enabled = true
token   = "change-this-token-value"
